# Generated by Django 3.0.5 on 2020-12-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200420_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (1, 'Used - Like New'), (0, 'Brand New'), (4, 'Used - Not Usable')], default=4),
        ),
    ]
