# Generated by Django 3.0.5 on 2020-12-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20201210_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(2, 'Used - Good'), (3, 'Used - Poor Condidtion'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (0, 'Brand New')], default=4),
        ),
    ]
