# Generated by Django 3.0.5 on 2020-12-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20201211_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(1, 'Used - Like New'), (3, 'Used - Poor Condidtion'), (0, 'Brand New'), (4, 'Used - Not Usable'), (2, 'Used - Good')], default=4),
        ),
    ]
