# Generated by Django 3.0.5 on 2020-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20201211_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Brand New'), (1, 'Used - Like New'), (4, 'Used - Not Usable'), (2, 'Used - Good'), (3, 'Used - Poor Condidtion')], default=4),
        ),
    ]
